// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSMonoDebugger
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSMonoDebugger2022PackageString = "a3c26381-6026-4adc-ac25-808c42614416";
        public static Guid guidVSMonoDebugger2022Package = new Guid(guidVSMonoDebugger2022PackageString);

        public const string guidVSMonoDebuggerPackageCmdSetString = "becf5dd2-041f-4b6e-9c6f-bb38538fc1d7";
        public static Guid guidVSMonoDebuggerPackageCmdSet = new Guid(guidVSMonoDebuggerPackageCmdSetString);

        public const string BatchCheckIn_16xString = "a6146350-5354-4abe-b452-fb63881c9293";
        public static Guid BatchCheckIn_16x = new Guid(BatchCheckIn_16xString);

        public const string DebugTemplate_16xString = "6bec4581-8f59-4a3f-ba52-723454ef06d4";
        public static Guid DebugTemplate_16x = new Guid(DebugTemplate_16xString);

        public const string DownloadLog_16xString = "e48e1f6f-b26c-460a-86df-69904236b876";
        public static Guid DownloadLog_16x = new Guid(DownloadLog_16xString);

        public const string Settings_16xString = "f0e24d10-a061-470f-8162-892ed3bb1abf";
        public static Guid Settings_16x = new Guid(Settings_16xString);

        public const string StartRemoteDebugger_16xString = "95f6fdc3-da9f-4266-bd63-1a02ecccbcdf";
        public static Guid StartRemoteDebugger_16x = new Guid(StartRemoteDebugger_16xString);

        public const string Process_16xString = "20e883f0-e7ee-4444-b9b4-67f2892b3d0d";
        public static Guid Process_16x = new Guid(Process_16xString);

        public const string BuildSelection_16xString = "c6d5524b-6ccf-4fc9-9bcf-a057bfb2afa6";
        public static Guid BuildSelection_16x = new Guid(BuildSelection_16xString);

        public const string guidImagesString = "dbc7ea16-7046-43f8-9340-6f5b33994514";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MonoMainMenu = 0x1000;
        public const int MonoMainMenuGroupLevel1 = 0x1100;
        public const int MonoMainMenuGroupLevel2 = 0x1200;
        public const int cmdDeployAndDebugOverSSH = 0x1001;
        public const int cmdDeployOverSSH = 0x1002;
        public const int cmdDebugOverSSH = 0x1003;
        public const int cmdOpenLogFile = 0x1004;
        public const int cmdOpenDebugSettings = 0x1005;
        public const int cmdAttachToMonoDebuggerWithoutSSH = 0x1006;
        public const int cmdBuildProjectWithMDBFiles = 0x1007;
        public const int imgDeployOnly = 0x0001;
        public const int imgDebugOnly = 0x0001;
        public const int imgShowLogfile = 0x0001;
        public const int imgSettings = 0x0001;
        public const int imgDeployAndDebug = 0x0001;
        public const int imgAttachToMonoDebuggerWithoutSSH = 0x0001;
        public const int imgBuildProjectWithMDBFiles = 0x0001;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
    }
}